package ru.drrey.babyname.navigationmediator

import ru.drrey.babyname.navigation.SimpleFlowScreenProvider

interface AuthFlowScreenProvider : SimpleFlowScreenProvider
interface NamesFlowScreenProvider : SimpleFlowScreenProvider
interface PartnersQrCodeFlowScreenProvider : SimpleFlowScreenProvider
interface AddPartnerFlowScreenProvider : SimpleFlowScreenProvider
interface ResultsFlowScreenProvider : SimpleFlowScreenProvider