package ru.drrey.babyname.navigationmediator

import ru.drrey.babyname.navigation.SimpleFlowScreenProvider

interface WelcomeFlowScreenProvider : SimpleFlowScreenProvider
interface AuthFlowScreenProvider : SimpleFlowScreenProvider
interface NamesFlowScreenProvider : SimpleFlowScreenProvider
interface FilterFlowScreenProvider : SimpleFlowScreenProvider
interface PartnersQrCodeFlowScreenProvider : SimpleFlowScreenProvider
interface AddPartnerFlowScreenProvider : SimpleFlowScreenProvider
interface ResultsFlowScreenProvider : SimpleFlowScreenProvider